#define PIN_ALARM_BUZZER 2
#define PIN_ALARM_LED 3
#define PIN_STATE_LED 4
#define PIN_RELAY 5

#define PIN_SENSOR_LED_1 6
#define PIN_SENSOR_LED_2 7
#define PIN_SENSOR_LED_3 8
#define PIN_SENSOR_LED_4 9

#define PIN_SENSOR_CHECK_1 10
#define PIN_SENSOR_CHECK_2 11
#define PIN_SENSOR_CHECK_3 12
#define PIN_SENSOR_CHECK_4 13

#define PIN_BUTTON A0

#define PIN_SENSOR_1 A1
#define PIN_SENSOR_2 A2
#define PIN_SENSOR_3 A3
#define PIN_SENSOR_4 A4

#define FLOOD_LEVEL 900
#define RELAY_DURATION 5000
#define INITIAL_STATE HIGH