#define PIN_RELAY 4
#define PIN_BUTTON A0
#define PIN_ALARM_LED 3
#define PIN_ALARM_BUZZER 2

#define PIN_SENSOR_1 A1
#define PIN_SENSOR_2 A2
#define PIN_SENSOR_3 A3
#define PIN_SENSOR_4 A4

#define PIN_SENSOR_LED_1 5
#define PIN_SENSOR_LED_2 6
#define PIN_SENSOR_LED_3 7
#define PIN_SENSOR_LED_4 8

#define FLOOD_LEVEL 100
#define RELAY_DURATION 5000
#define RELAY_INITIAL_STATE HIGH